package yourmedicines.processor.domain.medicineleaflet;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

/*
*This table keep information about paragraphs assigned to leaflet. Every record is one paragraph
*  */
@Entity
@Table(name = "PARAGRAPH")
public class Paragraph {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column
    @NotNull(message = "Title of the paragraph cannot be null")
    private String title;
    @Column(name="CONTENT", length = 4096)
    @NotNull(message = "Text message for paragraph cannot be null")
    private String text;
    @Column
    @NotNull(message = "Uniqe medicine id cannot be null")
    private String medicineId;
    @Column
    @NotNull(message = "Display order cannot be null (but it should be autogenerated!)")
    private int displayOrder;
    @CreationTimestamp
    private Timestamp createdDate;
    @Column(name = "ModifiedDate")
    @UpdateTimestamp
    private Timestamp modifiedDate;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId;
    }

    public int getDisplayOrder() {
        return displayOrder;
    }

    public void setDisplayOrder(int displayOrder) {
        this.displayOrder = displayOrder;
    }
}
